name: Fomat Md 
on: push
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkou code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
        
      - name: Run Prettier 
        run: npx prettier --check README.md
