name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env: 
      USERNAME: ${{ secrets.USERNAME }}
    steps:
      - run: echo "{USERNAME}" # ログ出力はマスクされる
      - run: echo "{USERNAME:0:1} ${USERNAME#?}" # ログ出力はマスクされない
